services:
  easyfile-api:
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: easyfile-api
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - AWS__AccessKey=${AWS_ACCESS_KEY}
      - AWS__SecretKey=${AWS_SECRET_KEY}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./EasyFile/Logs:/app/Logs

  easyfile-web:
    build:
      context: ./easyfile-frontend
      dockerfile: Dockerfile
    container_name: easyfile-web
    depends_on:
      - easyfile-api
    ports:
      - "3000:80"
    volumes:
      - ./easyfile-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true