services:
  easyfile-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: easyfile-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${LOCAL_DB_PASSWORD:-EasyFile_local_123!}
    ports:
      - "1433:1433"
    volumes:
      - easyfile-sqlserver-data:/var/opt/mssql

  easyfile-api:
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: easyfile-api
    depends_on:
      - easyfile-db
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING_LOCAL}
      - AWS__AccessKey=${AWS_ACCESS_KEY}
      - AWS__SecretKey=${AWS_SECRET_KEY}
      - AWS__Region=${AWS_REGION}
      - AWS__BucketName=${AWS_BUCKET_NAME}
      - EmailSettings__SendGridApiKey=${SENDGRID_API_KEY}
      - EmailSettings__SenderEmail=${SENDGRID_SENDER_EMAIL}
      - Frontend__BaseUrl=http://localhost:3000
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./EasyFile/Logs:/app/Logs

  easyfile-web:
    build:
      context: ./easyfile-frontend
      dockerfile: Dockerfile
    container_name: easyfile-web
    depends_on:
      - easyfile-api
    ports:
      - "3000:80"
    volumes:
      - ./easyfile-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  easyfile-sqlserver-data:
