using EasyFile.Interfaces;
using Microsoft.Extensions.Configuration;
using OpenAI.Chat;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace EasyFile.Services
{
    public class AiReviewService : IAiReviewService
    {
        private readonly string _apiKey;

        // We inject IConfiguration to securely grab the key from appsettings.json
        public AiReviewService(IConfiguration configuration)
        {
            _apiKey = configuration["OpenAI:ApiKey"] 
                      ?? throw new ArgumentNullException("OpenAI API Key is missing.");
        }

        public async Task<string> GenerateDocumentReportAsync(string documentText)
        {
            // gpt-4o-mini is OpenAI's fastest and most cost-effective model for text tasks
            var client = new ChatClient("gpt-4o-mini", _apiKey);

            var messages = new List<ChatMessage>
            {
                new SystemChatMessage(
                    "You are an expert legal document analyzer. " +
                    "Step 1: Determine if the provided text is from a valid legal document (e.g., court filing, affidavit, contract, subpoena). " +
                    "If the text is NOT a legal document (e.g., a recipe, a random photo, blank pages, casual conversation), reply EXACTLY and ONLY with the phrase: 'REJECT_NON_LEGAL_DOCUMENT'. " +
                    "Step 2: If it IS a legal document, extract the key details in a clean, bulleted list. Include items like Case Name, Case Number, and Document Title. If a detail is missing, state 'Not Found'."
                ),
                new UserChatMessage($"Here is the document text to review:\n\n{documentText}")
            };

            var response = await client.CompleteChatAsync(messages);

            // Return the text generated by the AI
            return response.Value.Content[0].Text;
        }
    }
}